export const GET_ALL_BOOKS_SUCCESS = 'GET_ALL_BOOKS_SUCCESS'
export const GET_ALL_BOOKS_FAIL = 'GET_ALL_BOOKS_FAIL'

export const GET_ONE_BOOK_SUCCESS = 'GET_ONE_BOOK_SUCCESS'
export const GET_ONE_BOOK_FAIL = 'GET_ONE_BOOK_FAIL'

export const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS'
export const CREATE_BOOK_FAIL = 'GET_ONE_BOOK_FAIL'
