export const GET_ALL_REQUESTES_SUCCESS = 'GET_ALL_REQUESTES_SUCCESS'
export const GET_ALL_REQUESTES_FAIL = 'GET_ALL_REQUESTES_FAIL'

export const CREATE_REQUEST_SUCCESS = 'CREATE_REQUEST_SUCCESS'
export const CREATE_REQUEST_FAIL = 'CREATE_REQUEST_FAIL'