export const CREATE_USER = 'CREATE_USER'
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL'

export const MODIFY_USER = 'MODIFY_USER'

export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL'

export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL'

export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE'
export const EDIT_USER_PROFILE_FAIL = 'EDIT_USER_PROFILE_FAIL'
